services:
  database:
    image: postgres:latest
    container_name: finance_db 
    environment:
      POSTGRES_USER: project 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: finance 
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/test_data_db.sql:/docker-entrypoint-initdb.d/test_data_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped 
volumes:
  db_data: