services:
  finance:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./config.toml:/usr/local/bin/config.toml
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_CLI_COLORS: ${ROCKET_CLI_COLORS}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./database/test_data_db.sql:/docker-entrypoint-initdb.d/test_data_db.sql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  postgres_data: